apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-wms
  name: locust-wms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-wms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: locust-wms
    spec:
      containers:
      - image: eduardrosert/locust-wms-test
        imagePullPolicy: IfNotPresent
        name: locust-wms
        env:
        - name: WMS_SERVICE_URL
          value: "https://example.com/wms"
        #- name: WMS_ACCESS_KEY
        #  value: "myauthkey=mysecretaccesstoken"
        command: ["/bin/bash", "-c"]
        args: [ "locust -f /app/wms-load-test/locustfile.py --host=$WMS_SERVICE_URL"]
        resources: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-wms
  name: locust-wms
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: locust-wms
  type: NodePort